# Generated by Django 3.2.25 on 2025-02-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_auto_20250208_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
