# Generated by Django 3.2.25 on 2025-02-11 00:23

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_alter_plot_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Plot', 'verbose_name_plural': 'Plots'},
        ),
        migrations.AlterField(
            model_name='plot',
            name='area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Area (ha)'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('cereals', 'Cereals'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('other', 'Other')], max_length=255, verbose_name='Crop Type'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='exploitation',
            field=models.CharField(default='', max_length=255, verbose_name='Exploitation'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='has_manager',
            field=models.BooleanField(default=False, verbose_name='Has Manager'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Plot Name'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['name'], name='plots_plot_name_fe95ba_idx'),
        ),
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['exploitation'], name='plots_plot_exploit_3263a7_idx'),
        ),
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['crop_type'], name='plots_plot_crop_ty_a35d98_idx'),
        ),
    ]
