# Generated by Django 3.2.25 on 2025-02-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_auto_20250211_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('ble_dur', 'Blé dur'), ('ble_tendre', 'Blé tendre'), ('orge', 'Orge'), ('mais', 'Maïs'), ('tournesol', 'Tournesol'), ('colza', 'Colza'), ('feve', 'Fève'), ('pois_chiche', 'Pois chiche'), ('lentille', 'Lentille'), ('betterave', 'Betterave sucrière'), ('canne_sucre', 'Canne à sucre'), ('coton', 'Coton'), ('luzerne', 'Luzerne'), ('mais_fourrager', 'Maïs fourrager'), ('bersim', 'Bersim'), ('pomme_terre', 'Pomme de terre'), ('tomate', 'Tomate'), ('oignon', 'Oignon'), ('carotte', 'Carotte'), ('poivron', 'Poivron'), ('courgette', 'Courgette'), ('piment', 'Piment'), ('aubergine', 'Aubergine'), ('melon', 'Melon'), ('pasteque', 'Pastèque'), ('olivier', 'Olivier'), ('agrumes', 'Agrumes'), ('amandier', 'Amandier'), ('pommier', 'Pommier'), ('vigne', 'Vigne'), ('grenadier', 'Grenadier'), ('figuier', 'Figuier'), ('abricotier', 'Abricotier'), ('prunier', 'Prunier')], max_length=50, verbose_name='Crop Type'),
        ),
    ]
