# Generated by Django 3.2.25 on 2025-02-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_alter_plot_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('cereals', 'Cereals'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('other', 'Other')], max_length=255, verbose_name='Crop Type'),
        ),
    ]
